title: Jindong Pan # your name (or website title) here
logo: "images/myprofile_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Let's work togethor to make data more meaningful to our life 
  <br><br>
  All comments are welcome:
- Medical professional can feedback at our [medical professional wiki page](https://github.com/cancer-research-data-inside/lymphoma/wiki/Medical-professional-discussion-page).
- Data scientist comments go [data analysis wiki page](https://github.com/cancer-research-data-inside/lymphoma/wiki/data-analysis-discussion-page).
- Other comments go [guest wiki page](https://github.com/cancer-research-data-inside/lymphoma/wiki/Guest-wiki-page).

  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-160756435-1 # your Google Analytics tracking ID here
